### ISSUE TITLE
how to test CorLoc, could you show me the code?

### ISSUE THREAD

**Issue by yuxinyan** [ppengtang/oicr#1]
I want to test CorLoc, could you give me the test code? 
Also i found the training is time-consuming, i trained 70000 iterations on VGG16 with Titan X. It costs me 3 days to finish the whole training period, is it right?

**Comment by yuxinyan** [comment]
Could you give me the  oicr pre-trained model and the corresponding log file?

**Comment by ppengtang** [comment]
Actually the code for testing CorLoc can be found under the VOCdevkit folder. The usage is similar to the official PASCAL VOC mAP evaluation codes. As the dilated conv is very time-consuming, the 3 days training is reasonable. Maybe you can try to remove the dilated conv, but this may result in a little drop of performance.
I'm sorry that I have deleted the pre-trained models. I only re-train a VGG_M model on PASCAL VOC 2007. If you want I can send it to you.

**Comment by kilakila-heart** [comment]
@ppengtang can you also give me a pre-trained model？Or, if possible, all  code,thanks very much!My email:23020151154014@stu.xmu.edu.cn

**Comment by ppengtang** [comment]
I'm sorry that I have deleted our models.
All codes are available at github.
You can use our released codes to re-train the models.
