### ISSUE TITLE
Check failed: result == ncclSuccess (2 vs. 0)  unhandled system error

### ISSUE THREAD

**Issue by serena9525** [ppengtang/oicr#10]
Hi Peng Tang,
I tried running your multi-gpu PCL code, and got the error 
F0118 23:24:48.788218 37264 parallel.cpp:135] Check failed: result == ncclSuccess (2 vs. 0)  unhandled system error. *** Check failure stack trace: ***     I tried cuda9 and cuda8, got the same problem. Have you encountered this? Do you have any suggestions?

Thanks in advance.

**Comment by ppengtang** [comment]
Hi Siwen,

I have not met this problem before. Maybe you can search on the Internet to find a possible solution.

Best,
Peng

**Comment by qingyang-jiandao** [comment]
I have  met this problem，Have you encountered this? Do you have any suggestions?

**Comment by ppengtang** [comment]
I feel sorry for that I have not met this problem before. Maybe you can search on the Internet to find a possible solution.
