### ISSUE TITLE
matlab version n custom data training

### ISSUE THREAD

**Issue by dedoogong** [ppengtang/oicr#11]
Hello! Thank you very much for sharing this nice work. 
First, could you please tell me which Matlab version you use(maybe recent version would not work well with caffe). 
Second, I have some custom dataset and I want to train PCL with it(my data also has VOC label format). 
Then, I guess I need to prepare proposal boxes file generated by selective search algorithm. Can you let me know which code did you use? Fast/er RCNN repo also have that source? maybe I need to use Matlab?

Please give me some hints. 

I'm considering merge your work with mine to improve my network. 

Thank you in advance!

**Comment by ppengtang** [comment]
Hi, thanks for your interesting in our work. The answers are listed in the following.

1. In my experiments, I don't use matcaffe. Instead, I use pycaffe, with Python 2.7.
2. You can follow the codes in the [R-CNN repo](https://github.com/rbgirshick/rcnn/blob/master/selective_search/selective_search_boxes.m) to generate proposals. I think any version of Matlab can work well for proposal generation.

**Comment by dedoogong** [comment]
thank you very much for your light speed feed back~!
