### ISSUE TITLE
Out of memory in training VGG16-based models

### ISSUE THREAD

**Issue by naoto0804** [ppengtang/oicr#2]
Hello.
I'd like to ask just a quick question.

When I set up all the requirements and run the training code of oicr below using single Titan X, Check failed: error == cudaSuccess (2 vs. 0)  out of memory error occurs.
```
$ ./tools/train_net.py --gpu 0 --solver models/VGG16/solver.prototxt --weights data/imagenet_models/VGG16.v2.caffemodel --iters 70000
```

It seems that this network consumes almost 25G memories and cannot be trained on single Titan X.
Is it correct?
Thanks in advance!

**Comment by ppengtang** [comment]
All of our experiments are carried out on a single Titan X GPU. Therefore, one single Titanx can meet the needs of GPU memory for VGG16.
Which proposal methods you have tried? Selective Search or EdgeBoxes? Maybe more proposals will result in larger GPU memory requirement.
And have you tried to use the CUDNN for caffe? Using the CUDNN will reduce the memory cost.

Hope this will help you.

**Comment by naoto0804** [comment]
Oh, I've completely forgotten to set CUDNN=1 in compiling caffe.
Now I can train VGG-16 based models using proposal generated by Selective Search on a single GPU.
Thank you so much for helping !!

**Comment by ppengtang** [comment]
You're welcome. Feel free to contact me if there is any other problem.
