### ISSUE TITLE
how to get OICR_ENS

### ISSUE THREAD

**Issue by fly6464** [ppengtang/oicr#3]
Hi, 

Thanks for releasing your code. Would you also provide details about how to get OIRC_ENS? In the paper, you mentioned you just sum up scores produced by VGG_M and VGG16 models. What do you do with the combined score when you train a Fast-RCNN model? The combined scores may be bigger than 1.

Thanks!

**Comment by ppengtang** [comment]
After obtaining the combined scores, we select the top-scoring proposal for each positive class as the pseudo groundtruths to train the fast rcnn, and do not use the combined scores anymore.

**Comment by fly6464** [comment]
Thanks for your help!

**Comment by XuYunqiu** [comment]
> After obtaining the combined scores, we select the top-scoring proposal for each positive class as the pseudo groundtruths to train the fast rcnn, and do not use the combined scores anymore.

Hi, I am trying to re-train my fast R-CNN. But I find the performance drops. 
"The top-scoring proposal for each positive class" means only 1 proposal with highest score will be selected for each positive class per image. Is this correct?

**Comment by ppengtang** [comment]
> "The top-scoring proposal for each positive class" means only 1 proposal with highest score will be selected for each positive class per image. Is this correct?

Yes, this is correct.
Maybe you can try to add dilated convolution in Fast R-CNN, or using more sophisticated methods to obtain pseudo ground truths and train fully-supervised detectors, such as [a].

[a] W2f: A weakly-supervised to fully-supervised framework for object detection
