### ISSUE TITLE
Minor issues during repro

### ISSUE THREAD

**Issue by vadimkantorov** [ppengtang/oicr#6]
1. Had to rename `lib/utils/bbox.pyx` to `lib/utils/cython_bbox.pyx` and `lib/utils/bbox.pyx` to `lib/utils/cython_bbox.pyx` (and fix `setup.py`) in order to match extension names in `lib/setup.py`. Otherwise I was getting an import error reported at https://stackoverflow.com/questions/8024805/cython-compiled-c-extension-importerror-dynamic-module-does-not-define-init-fu.

2. Add `import google.protobuf.text_format` to `lib/fast-rcnn/train.py` in order to avoid error reported in https://github.com/rbgirshick/py-faster-rcnn/issues/198

**Comment by ppengtang** [comment]
Thanks for your comments.

1. I have tried it on many different computers, and the "lib/utils/bbox.pyx" works for me. I don't know what happened.

2. Yes. Actually I have also found this problem. The "import google.protobuf as pb2" works for my older computer but don't work on my new computer. I have changed it to "from google.protobuf import text_format".

**Comment by vadimkantorov** [comment]
1. I guess changing the extension names to `utils.bbox` / `utils.nms` will work as well. Probably this quirk is related to Cython version or something like that.
2. Cool, thanks!

I'm trying to have a minimal repro. In the scripts and the paper you run the net for 70K iterations. Can I use, say 10K/5K/1K to observe the benefit of instance refinement? Do I understand correctly that to control the number of iterations of refinement it suffices to change https://github.com/ppengtang/oicr/blob/243206ced0bd8e4f20439bdd7aaf9a430e3b9cc2/lib/fast_rcnn/test_train.py#L138, https://github.com/ppengtang/oicr/blob/243206ced0bd8e4f20439bdd7aaf9a430e3b9cc2/lib/fast_rcnn/test_train.py#L157 and to comment out the loss functions from the corresponding solver.txt?

**Comment by ppengtang** [comment]
I'm not sure about the less iterations. I guess 10K can observe some improvements. Actually for the PASCAL VOC 2007 dataset, training 50K iterations (instead of 70K) is enough (decreasing the learning rate after 40K iterations).

To change the number of training iterations, we can change the `stepsize: 40000` in the solver.prototxt, and also change the 70000 in `./tools/train_net.py --gpu 1 --solver models/VGG16/solver.prototxt \
	--weights data/imagenet_models/$VGG16_model_name --iters 70000` to the desired number of iterations.

If the number of iterations is changed, the classifier and CNN features (conv1-fc7) are less effective, thus the "scores_tmp = blobs_out['ic_prob'] + blobs_out['ic_prob1'] + blobs_out['ic_prob2']" will change.

I'm sorry that I'm not sure about whether I understand you questions correctly.
I hope these can help you.

**Comment by vadimkantorov** [comment]
Received this error when running
```shell
python ./tools/test_net.py --def models/VGG16/test.prototxt --net output/default/voc_2007_trainval/vgg16_oicr_iter_10000.caffemodel --imdb voc_2007_trainval
```

```
Writing aeroplane VOC results file
Traceback (most recent call last):
  File "./tools/test_net.py", line 89, in <module>
    test_net_train(net, imdb)
  File ".../oicr/tools/../lib/fast_rcnn/test_train.py", line 275, in test_net_train
    imdb.evaluate_discovery(all_boxes, output_dir)
  File ".../oicr/tools/../lib/datasets/pascal_voc.py", line 331, in evaluate_discovery
    self._write_voc_results_file(all_boxes)
  File ".../oicr/tools/../lib/datasets/pascal_voc.py", line 212, in _write_voc_results_file
    with open(filename, 'wt') as f:
IOError: [Errno 2] No such file or directory: '.../oicr/tools/../lib/datasets/../../data/VOCdevkit2007/results/VOC2007/Main/comp4_39a738cf-c59b-4e97-86d6-327cb3efc77a_det_trainval_aeroplane.txt'
```

This directory exists: `.../oicr/tools/../lib/datasets/../../data/VOCdevkit2007/results/VOC2007`, but the `Main` sub-directory is not there.

**Comment by ppengtang** [comment]
Thanks for your comments.
Actually there should be a directory `VOCdevkit2007/results/VOC2007/Main`.
I have updated the code to avoid requiring make such directory manually.

**Comment by vadimkantorov** [comment]
A typo in a comment in `models/VGG16/test.prototxt`:
`0.125 # 1/16` should be `1/8`, right?

**Comment by ppengtang** [comment]
You are right.
I have fixed them.
Thank you.

**Comment by vadimkantorov** [comment]
I'm working on an effort to allow your code to run with PyTorch as a backend. I developed a tool allowing an easy switch: http://github.com/vadimkantorov/caffmodel2pytorch. Evaluation mode runs OK.

Now I'm trying to reimplement WeightedSoftmaxWithLoss and OICRLayer in PyTorch to enable training. I'm having difficulties parsing https://github.com/ppengtang/caffe/blob/c68ee001163b0f2eaa59b14d0ed9c4a1dd7c8ed7/src/caffe/layers/weighted_softmax_loss_layer.cu#L24-L25:
```cpp
template <typename Dtype>
__global__ void WeightedSoftmaxLossForwardGPU(const int nthreads,
          const Dtype* prob_data, const Dtype* label, const Dtype* weights,
          Dtype* loss, const int num, const int dim, const int spatial_dim,
          const bool has_ignore_label_, const int ignore_label_,
          Dtype* counts) {
  CUDA_KERNEL_LOOP(index, nthreads) {
    const int n = index / spatial_dim;
    const int s = index % spatial_dim;
    const int label_value = static_cast<int>(label[n * spatial_dim + s]);
      loss[index] = -weights[n] * log(max(prob_data[n * dim + label_value * spatial_dim + s],
                      Dtype(FLT_MIN)));
    
  }
}
```

I would be very grateful if you have time to comment on the expression above:
1. What are the dimensions of `weights` (`(R, )` ?), `prob_data` (`(R, C+1)`?), `label` (`(R, )`?)?
3. What are `n` (roi index?), `label_value` (class index?), `s` (dummy index in batch, always zero?)?
4. Which [`normalization_mode`](https://github.com/ppengtang/caffe/blob/c68ee001163b0f2eaa59b14d0ed9c4a1dd7c8ed7/src/caffe/layers/weighted_softmax_loss_layer.cpp#L60) is used in practice? VALID?

Thanks a lot!

**Comment by ppengtang** [comment]
Hi, 

Thanks for your efforts.

The WeightedSoftmaxWithLossLayer is a modified version of the SoftmaxWithLossLayer in the original caffe.

Suppose the input to the layer is a _NxCxWxH_ map (bottom[0]), where the _N_ is the batch size (_R_ here), the _C_ is the channel dimension (the number of classes here), the _W, H_ are width and height (both are 1 here).
It first will be passed through a softmax layer to obtain the `prob_`. The softmax can along four different directions (_N, C, W, H_), we use _a, b, c, d_ here. Suppose the softmax is along the _K_ direction, the `outer_num_` is the number between the _a-K_, the `inner_num_` is the number between _K-d_, for example, if the softmax is along the channel direction (i.e. _K=b_), then _outer_num_=N_, _inner_num_= W*H_. Thus the `prob_` is _NxCxWxH_.

We want the number of `labels` equals to the _outer_num_*inner_num__, and the number of `cls_loss_weights` equals to the _outer_num__.
Specially, in our case, the `outer_num_` is the roi count, `inner_num_` is equals to 1. So the `i` is the roi index, the `j` always equals to 0.

We use the default normalization_mode, [LossParameter_NormalizationMode_VALID](https://github.com/ppengtang/caffe/blob/c68ee001163b0f2eaa59b14d0ed9c4a1dd7c8ed7/src/caffe/layers/weighted_softmax_loss_layer.cpp#L64-L70).

I hope this can help you.

**Comment by vadimkantorov** [comment]
It's now clear. Thanks!

An unrelated question: is it normal that GPU memory consumption grows by 1Gb  (from 9300 Mb to 10300 Mb) over first 300 iterations of optimization? Is it just related to some maximum scale used and the number of ROIs?

**Comment by ppengtang** [comment]
Welcome.

Yes, in my experiments, the GPU memory will grow during some first iterations.
I agree that the reasons are related to some maximum scale used and the number of ROIs.

By the way, if you have reproduced the OICR by PyTorch and plan to release the codes, maybe you can send the url to me and I can put it on my Github page.

**Comment by vadimkantorov** [comment]
I'm now testing the optimization with the PyTorch backend. So far it's kind of Frankenstein :) It's replacing caffe module with with a PyTorch backend implementing the interface of Caffe classes (caffe.Net, caffe.SGDSolver, caffe.Blob, etc) and wrapping the Caffe python layers you've written. The repo is https://github.com/vadimkantorov/caffemodel2pytorch

It's useful in my own work for understanding further the effect of the loss you proposed, but it's not a full idiomatic reimplementation using PyTorch. That said, I'll put in the repo above an example replacing the Caffe backend with PyTorch for OICR.

The only things from Caffe preventing me to run your code without any Caffe install is currently is your snippet that reads SolverParam to get `display`/`snapshot_prefix` and `net.save` method for snapshotting. If you read display/snapshot_prefix by a custom parsing logic, something like this (in `lib/fast_rcnn/train.py`):
```python
# from caffe.proto import caffe_pb2
import json

#self.solver_param = caffe_pb2.SolverParameter()
#with open(solver_prototxt, 'rt') as f:
#    text_format.Merge(f.read(), self.solver_param)

self.solver_param = json.loads('{' + '\n'.join(['"' + line.replace(':', '":').replace('\n', ',') for line in open(solver_prototxt) if not line.startswith('#')]).rstrip(',') + '}')

# then use self.solver_param['snapshot_prefix'] and self.solver_param['display']
```

Then I could implement `net.save` method (it would save to HDF5 still, I think), and Caffe dependency can be made optional.

I've tested the code above, it works and I've implemented the `net.save` method

**Comment by ppengtang** [comment]
Wonderful work!
I have put your repo in the README.

I'm sorry that I'm not sure how to display/snapshot_prefix by a custom parsing logic. It seems that opencv has an function names `cv2.dnn.readNetFromCaffe("prototxt", "model")`. I think this may help.

**Comment by vadimkantorov** [comment]
My backend isn't fully ready yet (the roi-pooling and loss reimpl isn't public yet), I think it's better not to direct users there yet.

I've tested this line of code, it works well:
`self.solver_param = json.loads('{' + '\n'.join(['"' + line.replace(':', '":').replace('\n', ',') for line in open(solver_prototxt) if not line.startswith('#')]).rstrip(',') + '}')`

With this, you only need to change `solver_param.display` to solver_param['display']

**Comment by ppengtang** [comment]
Got it.

If you want to make your codes public please tell me~

**Comment by vadimkantorov** [comment]
Will do soon :)

The diff for `lib/fast_rcnn/train.py` (if you wish to drop the usage of google protobuf / caffe here):
```
diff --git a/lib/fast_rcnn/train.py b/lib/fast_rcnn/train.py
index b668494..ad1e713 100755
--- a/lib/fast_rcnn/train.py
+++ b/lib/fast_rcnn/train.py
@@ -16,8 +16,7 @@ from utils.timer import Timer
 import numpy as np
 import os

-from caffe.proto import caffe_pb2
-from google.protobuf import text_format
+import json

 class SolverWrapper(object):
     """A simple wrapper around Caffe's solver.
@@ -35,9 +34,7 @@ class SolverWrapper(object):
             print ('Loading pretrained model '
                    'weights from {:s}').format(pretrained_model)
             self.solver.net.copy_from(pretrained_model)
-        self.solver_param = caffe_pb2.SolverParameter()
-        with open(solver_prototxt, 'rt') as f:
-            text_format.Merge(f.read(), self.solver_param)
+        self.solver_param = json.loads('{' + '\n'.join(['"' + line.replace(':', '":').replace('\n', ',') for line in open(solver_prototxt) if not line.startswith('#')]).rstrip(',') + '}')

         self.solver.net.layers[0].set_roidb(roidb)

@@ -52,7 +49,7 @@ class SolverWrapper(object):

         infix = ('_' + cfg.TRAIN.SNAPSHOT_INFIX
                  if cfg.TRAIN.SNAPSHOT_INFIX != '' else '')
-        filename = (self.solver_param.snapshot_prefix + infix +
+        filename = (self.solver_param['snapshot_prefix'] + infix +
                     '_iter_{:d}'.format(self.solver.iter) + '.caffemodel')
         filename = os.path.join(self.output_dir, filename)

@@ -70,7 +67,7 @@ class SolverWrapper(object):
             self.solver.step(1)

             timer.toc()
-            if self.solver.iter % (10 * self.solver_param.display) == 0:
+            if self.solver.iter % (10 * self.solver_param['display']) == 0:
                 print 'speed: {:.3f}s / iter'.format(timer.average_time)

             if self.solver.iter % cfg.TRAIN.SNAPSHOT_ITERS == 0:
```

**Comment by ppengtang** [comment]
Got it!
That looks wonderful!
Thanks you for teaching me these!

**Comment by vadimkantorov** [comment]
Converter and ROI pooling code open (look at the very bottom): https://github.com/vadimkantorov/caffemodel2pytorch/blob/master/README.md

After all, it should not even require modifications of `lib/fast_rcnn/train.py` listed above. Just adding an import at the top of `tools/train_net.py` / `tools/test_net.py`, that is all.

Feel free to test it if you have time.

**UPD** Fixing a couple bugs
**UPD 2** Fixed!

**Comment by ppengtang** [comment]
Great!
Can I put it in the README of the OICR code?

**Comment by vadimkantorov** [comment]
i'm running a final test, i'll let you know. but it even seems that the PyTorch backend is running somewhat faster :)

**Comment by ppengtang** [comment]
OK.

Maybe Caffe is out of date now, especially the Caffe version I used-it hasn't been maintained more than one year :)

**Comment by vadimkantorov** [comment]
repro ran well, publishing the link is safe and sound now

**Comment by ppengtang** [comment]
Great! I have added it in the README. Thanks for your efforts!

**Comment by vadimkantorov** [comment]
I have a question about the scores in test time: https://github.com/ppengtang/oicr/blob/master/lib/fast_rcnn/test_train.py#L138

You're using the `ic_prob` which is obtained by softmax across classes. Could you comment about this choice?

Original WSDDN uses either `midn_prob0` (softmax across rois) or `midn_prob0 * midn_prob1` (softmax across rois times softmax across classes).

**Comment by ppengtang** [comment]
For the refined instance classifiers, we only use a single fully-connected layer with a softmax (across classes) layer during training. Therefore during testing, only the `ic_prob` is used.

**Comment by vadimkantorov** [comment]
The `ic_prob` as defined below in `test.prototxt` to be used in testing, also computes softmax over classes, right?

```
layer {
  name: "ic_prob"
  type: "Softmax"
  bottom: "ic_score"
  top: "ic_prob"
}
```

This was a little counter-inuitive for me...

**Comment by ppengtang** [comment]
Yes. The `ic_prob `computes softmax over classes as in `test.prototxt`.

To my understanding, the softmax over rois is mainly to provide a weight for the proposal classification score (probability) pooling. But for the refined instance classifiers, we do not need to aggregate proposal classification scores (probabilities) into image scores (probabilities) to train the network. Thus only using the softmax over classes to compute the proposal classification score (probability) is enough.
