### ISSUE TITLE
out of memory problem

### ISSUE THREAD

**Issue by KunpengLi1994** [ppengtang/oicr#7]
Hi Peng Tang

Thanks for your great work. When I run the training code using:
```
./tools/train_net.py --gpu 1 --solver models/VGG16/solver.prototxt \
	--weights data/imagenet_models/$VGG16_model_name --iters 70000
```
I got following problem:
![train](https://user-images.githubusercontent.com/16794194/36053430-b2c7c5cc-0dbf-11e8-9762-b7bae3cd56ed.png)

I'm using TITAN XP with 12 G memory. And I find before the error, the memory was almost full:

![gpu](https://user-images.githubusercontent.com/16794194/36053646-6fe7d016-0dc0-11e8-8f10-ab5e49d6fff8.png)

Even I change the batch size by decreasing " iter_size" of the solver.prototxt from 2 to 1, the problem still exists.

![train2](https://user-images.githubusercontent.com/16794194/36053566-1bcd4c40-0dc0-11e8-9266-352727563cd9.png)

I would appreciate if you can help to figure out the problem. Thanks!

**Comment by ppengtang** [comment]
Thanks for your comments.

I have met the same problem using the TITAN XP GPU.

I think you can change the `__C.TRAIN.MAX_SIZE` [here](https://github.com/ppengtang/oicr/blob/master/lib/fast_rcnn/config.py#L37) to `1800` to avoid this problem. This would not decrease the performance a lot.
The `iter_size` would not influence the memory costing.

Actually when testing on the old version TITAN X GPU, there is no problem of "Out of Memory" and I don't know why.

Feel free to let me know if there is any other problem.

**Comment by ppengtang** [comment]
There is another thing. You should compile the Caffe with `USE_CUDNN := 1`. Please also see the issue [#2](https://github.com/ppengtang/oicr/issues/2).

**Comment by KunpengLi1994** [comment]
Yes, I forgot CUDNN. Compile the Caffe with USE_CUDNN := 1 do help to solve the problem. It takes 9.8G memory now. 

Thanks a lot!!

**Comment by ppengtang** [comment]
Welcome.

Feel free to contact me if there is any other question.
