### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by KunpengLi1994** [ppengtang/oicr#8]
Hi Peng Tang,

After running your training code successfully, I got the trained model with 70000 iterations. However, when I try do the testing by using 

`./tools/test_net.py --gpu 1 --def models/VGG16/test.prototxt \
  --net output/default/voc_2007_trainval/vgg16_oicr_iter_70000.caffemodel \
  --imdb voc_2007_trainval`

I got the following error:

![image](https://user-images.githubusercontent.com/16794194/36235887-22998d22-11c1-11e8-9242-ec6b83295bc2.png)

I also checked the detections.pkl file and found each component of the output is 
`array([], shape=(0, 5), dtype=float32)`

It' seems that the learned model doesn't work with no output. I would appreciate if you can help to check the error. Thanks!

**Comment by ppengtang** [comment]
Hi,

I'm not sure what happened. I haven't encountered this problem.

Have you changed the codes in the tools/test_net.py? It seems that you call the `test_net` function in [here](https://github.com/ppengtang/oicr/blob/master/tools/test_net.py#L87).
But when the imdb is `voc_2007_trainval`, it will call the `test_net_train` function in [here](https://github.com/ppengtang/oicr/blob/master/tools/test_net.py#L89). And the result files will be `discovery.pkl` and `discovery_all.pkl`, as in [here](https://github.com/ppengtang/oicr/blob/master/lib/fast_rcnn/test_train.py#L266-L273).

**Comment by KunpengLi1994** [comment]
Hi 

Thanks for your reply! 

I forgot to use the pre-trained model by modifying "--weights data/imagenet_models/$VGG16_model_name " to the corresponding model. Therefore, the model didn't learn anything useful and get no detection results. This may cause the same problem when training Fast-RCNN.
