### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jiangerxiaozhao** [ppengtang/oicr#9]
Caffe compiled successfully, but , when I was training, I was given an error：
Segmentation fault (core dumped)
Do you have any suggestions?

Also, can you tell me the version of the key dependencies?
protobuf opencv  numpy cython scikit-image  easydict...

Also, which python version？

**Comment by ppengtang** [comment]
We use Python 2.7. I use "pip install -r caffe/python/requirements.txt" and "pip install opencv-python" to install these libraries.
I think the version of protobuf opencv numpy cython scikit-image easydict... will not cause the segmentation fault. I have tried on different machines with different versions of protobuf opencv numpy cython scikit-image easydict..., and have not met the same problem.
I'm not sure the reasons of the problem. Could you provide more detailed log information?

**Comment by jiangerxiaozhao** [comment]
@ppengtang Thank you very much, your installation method worked.
